### ISSUE TITLE
possibly be resolved without consuming data

### ISSUE THREAD

**Issue by benlypan** [node-modules/stream-wormhole#3]
`stream._readableState.ended` would be set in function [`_stream_readable.onEofChunk`](https://github.com/nodejs/node/blob/a9e422eee2b32bfed38aa78845305aac06720712/lib/_stream_readable.js#L496) without emitting the `end` event. In this case, the stream is not ended truely.

**Comment by fengmk2** [comment]
Can you show me an example to repeat this bug?

**Comment by benlypan** [comment]
@fengmk2 
I got the bug when I test [ `Acquire Uploaded Files` demo of egg](https://eggjs.org/en/basics/controller.html#acquire-uploaded-files). In this demo, `await parts())` will be blocked after call `sendToWormhole`. It's interesting that the purpose of `sendToWormhole` in the case is to solve the blocking problem, as shown in the comment.

I found that the bug is appeared when using `sendToWormhole` together with `co-busboy`. The `await parts()` operation will wait the `end` event of the file stream, which `sendToWormhole` dost not trigger it(directly call resolve because of _readableState.ended). I don't know it's sendToWormhole's bug or co-busboy's bug, or even busboy's bug. But I think `sendToWormhole` should handle this case(_readableState.ended was set without any operation of consuming data or emitting end event), trigger an 'end' event by doing something.

I wrote an [example](https://github.com/benlypan/test-co-busboy) to repeat this bug. You can repeat the bug by posting a file to it, for example, using `curl -F "filename=@test.txt" http://localhost:3000`

**Comment by fengmk2** [comment]
https://github.com/node-modules/stream-wormhole/pull/7 I think we have fixed this bug, you can take a try the latest version.
