### ISSUE TITLE
这里是不是写错了

### ISSUE THREAD

**Issue by yashiro1899** [node-modules/stream-wormhole#4]
最后一行应该是 `error` 啊?
<img width="392" alt="screen shot 2018-05-05 at 14 59 02" src="https://user-images.githubusercontent.com/473662/39660608-2df1c3fe-5075-11e8-9b66-8355b191aa53.png">

**Comment by fengmk2** [comment]
@yashiro1899 感谢提醒。

https://github.com/node-modules/stream-wormhole/pull/6
